---
# This file is managed centrally by modulesync
#   https://github.com/theforeman/foreman-installer-modulesync
rvm:
  - 2.1.5
  - 2.0.0
  - 1.9.3
  - 1.8.7
env:
  - PUPPET_VERSION=4.0 ONLY_OS=centos-7-x86_64,ubuntu-14-x86_64,freebsd-10-amd64
  - PUPPET_VERSION=3.5 FUTURE_PARSER=yes TRUSTED_NODE_DATA=yes ONLY_OS=centos-7-x86_64,ubuntu-14-x86_64,freebsd-10-amd64
  - PUPPET_VERSION=3.5 ONLY_OS=centos-7-x86_64,ubuntu-14-x86_64,freebsd-10-amd64
  - PUPPET_VERSION=4.0 EXCLUDE_OS=centos-7-x86_64,ubuntu-14-x86_64,freebsd-10-amd64
  - PUPPET_VERSION=3.5 FUTURE_PARSER=yes TRUSTED_NODE_DATA=yes EXCLUDE_OS=centos-7-x86_64,ubuntu-14-x86_64,freebsd-10-amd64
  - PUPPET_VERSION=3.5 EXCLUDE_OS=centos-7-x86_64,ubuntu-14-x86_64,freebsd-10-amd64
  - PUPPET_VERSION=2.7.0 ONLY_OS=ubuntu-12-x86_64,centos-6-x86_64
matrix:
  fast_finish: true
  exclude:
    # No real support for Ruby 1.9.3 on Puppet 2.x
    - rvm: 1.9.3
      env: PUPPET_VERSION=2.7.0 ONLY_OS=ubuntu-12-x86_64,centos-6-x86_64
    # No support for Ruby 2.0 before Puppet 3.2
    - rvm: 2.0.0
      env: PUPPET_VERSION=2.7.0 ONLY_OS=ubuntu-12-x86_64,centos-6-x86_64
    # No support for Ruby 2.1 before Puppet 3.5
    - rvm: 2.1.5
      env: PUPPET_VERSION=2.7.0 ONLY_OS=ubuntu-12-x86_64,centos-6-x86_64
    # No support for Ruby 1.8.7 on Puppet 4.x
    - rvm: 1.8.7
      env: PUPPET_VERSION=4.0 ONLY_OS=centos-7-x86_64,ubuntu-14-x86_64,freebsd-10-amd64
    - rvm: 1.8.7
      env: PUPPET_VERSION=4.0 EXCLUDE_OS=centos-7-x86_64,ubuntu-14-x86_64,freebsd-10-amd64
bundler_args: --without development
sudo: false
